name: roadvision
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_3
  - _openmp_mutex=4.5=20_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py310h458dff3_0
  - blosc=1.21.6=h85f69ea_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.2.0=py310hd3493e3_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-blosc2=2.15.2=hb461149_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hcfcfb64_0
  - expat=2.7.4=hd7fb8db_0
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.61.1=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=h8276f4a_0
  - geopandas=1.1.2=pyhd8ed1ab_0
  - geopandas-base=1.1.2=pyha770c72_0
  - geos=3.13.0=h5a68840_0
  - geotiff=1.7.4=h887f4e7_0
  - giflib=5.2.2=h64bf75a_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2024.9.22=py310hee2158b_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jxrlib=1.1=hcfcfb64_3
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.22.2=h0ea6238_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.5=haf901d7_0
  - libarchive=3.7.7=h88ece9c_0
  - libavif16=1.3.0=ha08a409_3
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libcurl=8.18.0=h8206538_1
  - libde265=1.0.15=h91493d7_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_18
  - libgdal-core=3.10.0=ha193a43_5
  - libgomp=15.2.0=h8ee18e1_18
  - libheif=1.18.2=gpl_hc631cee_100
  - libhwloc=2.12.1=default_h88281d1_1000
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hb7713f0_4
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - libpng=1.6.55=h7351971_0
  - librttopo=1.1.0=hd4c2148_17
  - libspatialite=5.1.0=h939089a_12
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=hfc51747_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - libzopfli=1.0.3=h0e60522_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=h6a83c73_1002
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markupsafe=3.0.3=py310hdb0e946_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - minizip=4.0.6=hb638d1e_0
  - mkl=2025.3.0=hac47afa_455
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310h4987827_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.1=hf411b9b_1
  - osmnx=2.0.7=ha770c72_0
  - osmnx-base=2.0.7=pyhd8ed1ab_0
  - packaging=25.0=py310haa95532_1
  - pandas=2.3.3=py310hed136d8_2
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.3.0=py310hb3a2f59_3
  - pip=26.0.1=pyhc872135_0
  - proj=9.5.1=h4f671f6_0
  - pthread-stubs=0.4=h0e40799_1002
  - pyogrio=0.10.0=py310hf80745b_1
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyproj=3.7.1=py310h19d4cff_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.8.0=py310hb0944cc_0
  - qhull=2020.2=hc790b64_5
  - rasterio=1.4.3=py310h1c3512e_0
  - rav1e=0.7.1=ha073cba_3
  - requests=2.32.5=pyhcf101f3_1
  - rio-vrt=0.3.1=pyhd8ed1ab_1
  - scikit-image=0.25.2=py310hed136d8_2
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.10.2=py310haa95532_0
  - shapely=2.0.7=py310hde62f2e_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sqlite=3.51.1=hda9a48d_0
  - svt-av1=4.0.0=hac47afa_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2024.12.12=pyhd8ed1ab_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.1=py310h29418f3_0
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - x265=3.5=h2d74725_3
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - zfp=1.0.1=h2f0f97f_5
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zlib-ng=2.2.5=h32d8bfd_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - annotated-doc==0.0.4
      - anyio==4.12.1
      - anywidget==0.9.21
      - asttokens==3.0.1
      - bqplot==0.12.45
      - cffi==2.0.0
      - comm==0.2.3
      - cryptography==46.0.5
      - decorator==5.2.1
      - earthengine-api==1.7.14
      - eerepr==0.1.2
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - filelock==3.24.3
      - fsspec==2026.2.0
      - future==1.0.0
      - geemap==0.37.1
      - geocoder==1.38.1
      - google-api-core==2.30.0
      - google-api-python-client==2.190.0
      - google-auth==2.48.0
      - google-auth-httplib2==0.3.0
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.9.0
      - google-crc32c==1.8.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.2
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - ipyevents==2.0.4
      - ipyfilechooser==0.6.0
      - ipyleaflet==0.20.0
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - jupyter-leaflet==0.20.0
      - jupyterlab-widgets==3.0.16
      - markdown-it-py==4.0.0
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - narwhals==2.17.0
      - parso==0.8.6
      - plotly==6.5.2
      - prompt-toolkit==3.0.52
      - proto-plus==1.27.1
      - protobuf==6.33.5
      - psygnal==0.15.1
      - pure-eval==0.2.3
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pygments==2.19.2
      - pyperclip==1.11.0
      - pyshp==3.0.3
      - python-box==7.4.1
      - pyyaml==6.0.3
      - ratelim==0.1.6
      - rich==14.3.3
      - rsa==4.9.1
      - safetensors==0.7.0
      - scooby==0.11.0
      - segmentation-models-pytorch==0.5.0
      - shellingham==1.5.4
      - stack-data==0.6.3
      - sympy==1.14.0
      - timm==1.0.25
      - torch==2.10.0
      - torchvision==0.25.0
      - tqdm==4.67.3
      - traitlets==5.14.3
      - traittypes==0.2.3
      - typer==0.24.1
      - typer-slim==0.24.0
      - typing-extensions==4.15.0
      - uritemplate==4.2.0
      - wcwidth==0.6.0
      - widgetsnbextension==4.0.15
prefix: D:\Anaconda\envs\roadvision
